###################
#Utility Variables#
###################
var hammer = <ore:craftingToolHardHammer>;
var cutter = <ore:craftingToolWireCutter>;
var saw = <ore:craftingToolSaw>;
#########
#OreDict#
#########

#ingots
var ingotBeryllium = <ore:ingotBeryllium>;
var ingotMagnesium = <ore:ingotMagnesium>;
var ingotAluminium = <ore:ingotAluminium>;
var ingotSilicon = <ore:ingotSilicon>;
var ingotScandium = <ore:ingotScandium>;
var ingotTitanium = <ore:ingotTitanium>;
var ingotVanadium = <ore:ingotVanadium>;
var ingotChrome = <ore:ingotChrome>;
var ingotManganese = <ore:ingotManganese>;
var ingotIron = <ore:ingotIron>;
var ingotCobalt = <ore:ingotCobalt>;
var ingotNickel = <ore:ingotZinc>;
var ingotCopper = <ore:ingotCopper>;
var ingotZinc = <ore:ingotZinc>;
var ingotGallium = <ore:ingotGallium>;
var ingotRubidium = <ore:ingotRubidium>;
var ingotYttrium = <ore:ingotYttrium>;
var ingotNiobium = <ore:ingotNiobium>;
var ingotMolybdenum = <ore:ingotMolybdenum>;
var ingotPalladium = <ore:ingotPalladium>;
var ingotSilver = <ore:ingotSilver>;
var ingotIndium = <ore:ingotIndium>;
var ingotTin = <ore:ingotTin>;
var ingotAntimony = <ore:ingotAntimony>;
var ingotTellurium = <ore:ingotTellurium>;
var ingotCaesium = <ore:ingotCaesium>;
var ingotLanthanum = <ore:ingotLanthanum>;
var ingotCerium = <ore:ingotCerium>;
var ingotPraseodymium = <ore:ingotPraseodymium>;
var ingotNeodymium = <ore:ingotNeodymium>;
var ingotPromethium = <ore:ingotPromethium>;
var ingotSamarium = <ore:ingotSamarium>;
var ingotEuropium = <ore:ingotEuropium>;
var ingotGadolinium = <ore:ingotGadolinium>;
var ingotTerbium = <ore:ingotTerbium>;
var ingotDysprosium = <ore:ingotDysprosium>;
var ingotHolmium = <ore:ingotHolmium>;
var ingotErbium = <ore:ingotErbium>;
var ingotThulium = <ore:ingotThulium>;
var ingotYtterbium = <ore:ingotYtterbium>;
var ingotLutetium = <ore:ingotLutetium>;
var ingotTantalum = <ore:ingotTantalum>;
var ingotTungsten = <ore:ingotTungsten>;
var ingotOsmium = <ore:ingotOsmium>;
var ingotIridium = <ore:ingotIridium>;
var ingotPlatinum = <ore:ingotPlatinum>;
var ingotGold = <ore:ingotGold>;
var ingotLead = <ore:ingotLead>;
var ingotBismuth = <ore:ingotBismuth>;
var ingotThorium = <ore:ingotThorium>;
var ingotUranium235 = <ore:ingotUranium235>;
var ingotUranium238 = <ore:ingotUranium>;
var ingotPlutonium244 = <ore:ingotPlutonium>;
var ingotPlutonium241 = <ore:ingotPlutonium241>;
var ingotAmericium = <ore:ingotAmericium>;
var ingotNeutronium = <ore:ingotNeutronium>;
var ingotBronze = <ore:ingotBronze>;
var ingotBrass = <ore:ingotBrass>;
var ingotInvar = <ore:ingotInvar>;
var ingotElectrium = <ore:ingotElectrium>;
var ingotWroughtIron = <ore:ingotWroughtIron>;
var ingotSteel = <ore:ingotSteel>;
var ingotStainlessSteel = <ore:ingotStainlessSteel>;
var ingotPigIron = <ore:ingotPigIron>;
var ingotRedAlloy = <ore:ingotRedAlloy>;
var ingotBlueAlloy = <ore:ingotBlueAlloy>;
var ingotCupronickel = <ore:ingotCupronickel>;
var ingotNichrome = <ore:ingotNichrome>;
var ingotKanthal = <ore:ingotKanthal>;
var ingotMagnalium = <ore:ingotMagnalium>;
var ingotSolderingAlloy = <ore:ingotSolderingAlloy>;
var ingotBatteryAlloy = <ore:ingotBatteryAlloy>;
var ingotTungstenSteel = <ore:ingotTungstenSteel>;
var ingotOsmiridium = <ore:ingotOsmiridium>;
var ingotSunnarium = <ore:ingotSunnarium>;
var ingotAdamantium = <ore:ingotAdamantium>;
var ingotFluxedElectrum = <ore:ingotElectrumFlux>;
var ingotEnderium = <ore:ingotEnderium>;
var ingotHSLASteel = <ore:ingotHSLA>;
var ingotInfusedGold = <ore:ingotInfusedGold>;
var ingotNaquadah = <ore:ingotNaquadah>;
var ingotNaquadahAlloy = <ore:ingotNaquadahAlloy>;
var ingotEnrichedNaquadah = <ore:ingotNaquadahEnriched>;
var ingotNaquadria = <ore:ingotNaquadria>;
var ingotDuranium = <ore:ingotDuranium>;
var ingotTritanium = <ore:ingotTritanium>;
var ingotThaumium = <ore:ingotThaumium>;
var ingotMithril = <ore:ingotMithril>;
var ingotMidasium = <ore:ingotMidasium>;
var ingotAstralSilver = <ore:ingotAstralSilver>;
var ingotBlackSteel = <ore:ingotBlackSteel>;
var ingotDamascusSteel = <ore:ingotDamascusSteel>;
var ingotShadowIron = <ore:ingotShadowIron>;
var ingotShadowSteel = <ore:ingotShadowSteel>;
var ingotIronwood = <ore:ingotIronWood>;
var ingotMeteoricIron = <ore:ingotMeteoricIron>;
var ingotMeteoricSteel = <ore:ingotMeteoricSteel>;
var ingotDarkIron = <ore:ingotDarkIron>;
var ingotCobaltBrass = <ore:ingotCobaltBrass>;
var ingotUltimet = <ore:ingotUltimet>;
var ingotAnnealedCopper = <ore:ingotAnnealedCopper>;
var ingotFieryBlood = <ore:ingotFieryBlood>;
var ingotRedSteel = <ore:ingotRedSteel>;
var ingotBlueSteel = <ore:ingotBlueSteel>;
var ingotSterlingSilver = <ore:ingotSterlingSilver>;
var ingotRoseGold = <ore:ingotRoseGold>;
var ingotBlackBronze = <ore:ingotBlackBronze>;
var ingotBismuthBronze = <ore:ingotBismuthBronze>;
var ingotMagneticIron = <ore:ingotIronMagnetic>;
var ingotMagneticSteel = <ore:ingotSteelMagnetic>;
var ingotMagneticNeodymium = <ore:ingotNeodymiumMagnetic>;
var ingotVanadiumGallium = <ore:ingotVanadiumGallium>;
var ingotYttriumBariumCuprate = <ore:ingotYttriumBariumCuprate>;
var ingotNiobiumNitride = <ore:ingotNiobiumNitride>;
var ingotNiobiumTitanium = <ore:ingotNiobiumTitanium>;
var ingotChromiumDioxide = <ore:ingotChromiumDioxide>;
var ingotForce = <ore:ingotForce>;
var ingotDeepIron = <ore:ingotDeepIron>;
var ingotDesh = <ore:ingotDesh>;

#Wires
var wireCobalt = <gregtech:gt.blockmachines:1200>;
var wireLead = <gregtech:gt.blockmachines:1220>;
var wireTin = <gregtech:gt.blockmachines:1240>;
var wireZinc = <gregtech:gt.blockmachines:1260>;
var wireSolderingAlloy = <gregtech:gt.blockmachines:1280>;
var wireIron = <gregtech:gt.blockmachines:1300>;
var wireNickel = <gregtech:gt.blockmachines:1320>;
var wireCupronickel = <gregtech:gt.blockmachines:1340>;
var wireCopper = <gregtech:gt.blockmachines:1360>;
var wireAnnealedCopper = <gregtech:gt.blockmachines:1380>;
var wireKanthal = <gregtech:gt.blockmachines:1400>;
var wireGold = <gregtech:gt.blockmachines:1420>;
var wireElectrum = <gregtech:gt.blockmachines:1440>;
var wireSilver = <gregtech:gt.blockmachines:1460>;
var wireBlueAlloy = <gregtech:gt.blockmachines:1480>;
var wireNichrome = <gregtech:gt.blockmachines:1500>;
var wireSteel = <gregtech:gt.blockmachines:1520>;
var wireTungstenSteel = <gregtech:gt.blockmachines:1540>;
var wireTungsten = <gregtech:gt.blockmachines:1560>;
var wireAluminium = <gregtech:gt.blockmachines:1580>;
var wireOsmium = <gregtech:gt.blockmachines:1620>;
var wirePlatinum = <gregtech:gt.blockmachines:1640>;
var wireNaquadah = <gregtech:gt.blockmachines:1700>;
var wireNiobiumTitanium = <gregtech:gt.blockmachines:1720>;
var wireVanadiumGallium = <gregtech:gt.blockmachines:1740>;
var wireYttriumBariumCuprate = <gregtech:gt.blockmachines:1760>;
var wireRedAlloy = <gregtech:gt.blockmachines:2000>;

#################
#GregTech Plates#
#################
var GTplateBeryllium = <gregtech:gt.metaitem.01:17008>;
var GTplateMagnesium = <gregtech:gt.metaitem.01:17018>;
var GTplateAluminium = <gregtech:gt.metaitem.01:17019>;
var GTplateSilicon = <gregtech:gt.metaitem.01:17020>;
var GTplateScandium = <gregtech:gt.metaitem.01:17027>;
var GTplateTitanium = <gregtech:gt.metaitem.01:17028>;
var GTplateVanadium = <gregtech:gt.metaitem.01:17029>;
var GTplateChrome = <gregtech:gt.metaitem.01:17030>;
var GTplateManganese = <gregtech:gt.metaitem.01:17031>;
var GTplateIron = <gregtech:gt.metaitem.01:17032>;
var GTplateCobalt = <gregtech:gt.metaitem.01:17033>;
var GTplateNickel =<gregtech:gt.metaitem.01:17034>;
var GTplateCopper = <gregtech:gt.metaitem.01:17035>;
var GTplateZinc = <gregtech:gt.metaitem.01:17036>;
var GTplateGallium = <gregtech:gt.metaitem.01:17037>;
var GTplateRubidium = <gregtech:gt.metaitem.01:17043>;
var GTplateYttrium = <gregtech:gt.metaitem.01:17045>;
var GTplateNiobium = <gregtech:gt.metaitem.01:17047>;
var GTplateMolybdenum = <gregtech:gt.metaitem.01:17048>;
var GTplatePalladium = <gregtech:gt.metaitem.01:17052>;
var GTplateSilver = <gregtech:gt.metaitem.01:17054>;
var GTplateIndium = <gregtech:gt.metaitem.01:17056>;
var GTplateTin = <gregtech:gt.metaitem.01:17057>;
var GTplateAntimony = <gregtech:gt.metaitem.01:17058>;
var GTplateTellurium = <gregtech:gt.metaitem.01:17059>;
var GTplateCaesium = <gregtech:gt.metaitem.01:17062>;
var GTplateLanthanum = <gregtech:gt.metaitem.01:17064>;
var GTplateCerium = <gregtech:gt.metaitem.01:17065>;
var GTplatePraseodymium = <gregtech:gt.metaitem.01:17066>;
var GTplateNeodymium = <gregtech:gt.metaitem.01:17067>;
var GTplatePromethium = <gregtech:gt.metaitem.01:17068>;
var GTplateSamarium = <gregtech:gt.metaitem.01:17069>;
var GTplateEuropium = <gregtech:gt.metaitem.01:17070>;
var GTplateGadolinium = <gregtech:gt.metaitem.01:17071>;
var GTplateTerbium = <gregtech:gt.metaitem.01:17072>;
var GTplateDysprosium = <gregtech:gt.metaitem.01:17073>;
var GTplateHolmium = <gregtech:gt.metaitem.01:17074>;
var GTplateErbium = <gregtech:gt.metaitem.01:17075>;
var GTplateThulium = <gregtech:gt.metaitem.01:17076>;
var GTplateYtterbium = <gregtech:gt.metaitem.01:17077>;
var GTplateLuteium = <gregtech:gt.metaitem.01:17078>;
var GTplateTantalum = <gregtech:gt.metaitem.01:17080>;
var GTplateTungsten = <gregtech:gt.metaitem.01:17081>;
var GTplateOsmium = <gregtech:gt.metaitem.01:17083>;
var GTplateIridium = <gregtech:gt.metaitem.01:17084>;
var GTplatePlatinum = <gregtech:gt.metaitem.01:17085>;
var GTplateGold = <gregtech:gt.metaitem.01:17086>;
var GTplateLead = <gregtech:gt.metaitem.01:17089>;
var GTplateBismuth = <gregtech:gt.metaitem.01:17090>;
var GTplateThorium = <gregtech:gt.metaitem.01:17096>;
var GTplateUranium235 = <gregtech:gt.metaitem.01:17097>;
var GTplateUranium238 = <gregtech:gt.metaitem.01:17098>;
var GTplatePlutonium244 = <gregtech:gt.metaitem.01:17100>;
var GTplatePlutonium241 = <gregtech:gt.metaitem.01:17101>;
var GTplateAmericium = <gregtech:gt.metaitem.01:17103>;
var GTplateNeutronium = <gregtech:gt.metaitem.01:17129>;
var GTplateBronze = <gregtech:gt.metaitem.01:17300>;
var GTplateBrass = <gregtech:gt.metaitem.01:17301>;
var GTplateInvar = <gregtech:gt.metaitem.01:17302>;
var GTplateElectrium = <gregtech:gt.metaitem.01:17303>;
var GTplateWroughtIron = <gregtech:gt.metaitem.01:17304>;
var GTplateSteel = <gregtech:gt.metaitem.01:17305>;
var GTplateStainlessSteel = <gregtech:gt.metaitem.01:17306>;
var GTplatePigIron = <gregtech:gt.metaitem.01:17307>;
var GTplateRedAlloy = <gregtech:gt.metaitem.01:17308>;
var GTplateBlueAlloy = <gregtech:gt.metaitem.01:17309>;
var GTplateCupronickel = <gregtech:gt.metaitem.01:17310>;
var GTplateNichrome = <gregtech:gt.metaitem.01:17311>;
var GTplateKanthal = <gregtech:gt.metaitem.01:17312>;
var GTplateMagnalium = <gregtech:gt.metaitem.01:17313>;
var GTplateSolderingAlloy = <gregtech:gt.metaitem.01:17314>;
var GTplateTungstenSteel = <gregtech:gt.metaitem.01:17316>;
var GTplateOsmiridium = <gregtech:gt.metaitem.01:17317>;
var GTplateSunnarium = <gregtech:gt.metaitem.01:17318>;
var GTplateAdamantium = <gregtech:gt.metaitem.01:17319>;
var GTplateFluxedElectrum = <gregtech:gt.metaitem.01:17320>;
var GTplateEnderium = <gregtech:gt.metaitem.01:17321>;
var GTplateHSLASteel = <gregtech:gt.metaitem.01:17322>;
var GTplateInfusedGold = <gregtech:gt.metaitem.01:17323>;
var GTplateNaquadah = <gregtech:gt.metaitem.01:17324>;
var GTplateNaquadahAlloy = <gregtech:gt.metaitem.01:17325>;
var GTplateEnrichedNaquadah = <gregtech:gt.metaitem.01:17326>;
var GTplateNaquadria = <gregtech:gt.metaitem.01:17327>;
var GTplateDuranium = <gregtech:gt.metaitem.01:17328>;
var GTplateTritanium = <gregtech:gt.metaitem.01:17329>;
var GTplateThaumium = <gregtech:gt.metaitem.01:17330>;
var GTplateMithril = <gregtech:gt.metaitem.01:17331>;
var GTplateMidasium = <gregtech:gt.metaitem.01:17332>;
var GTplateAstralSilver = <gregtech:gt.metaitem.01:17333>;
var GTplateBlackSteel = <gregtech:gt.metaitem.01:17334>;
var GTplateDamascusSteel = <gregtech:gt.metaitem.01:17335>;
var GTplateShadowIron = <gregtech:gt.metaitem.01:17336>;
var GTplateShadowSteel = <gregtech:gt.metaitem.01:17337>;
var GTplateDarkIron = <gregtech:gt.metaitem.01:17342>;
var GTplateCobaltBrass = <gregtech:gt.metaitem.01:17343>;
var GTplateUltimet = <gregtech:gt.metaitem.01:17344>;
var GTplateAnnealedCopper = <gregtech:gt.metaitem.01:17345>;
var GTplateFieryBlood = <gregtech:gt.metaitem.01:17346>;
var GTplateRedSteel = <gregtech:gt.metaitem.01:17348>;
var GTplateBlueSteel = <gregtech:gt.metaitem.01:17349>;
var GTplateSterlingSilver = <gregtech:gt.metaitem.01:17350>;
var GTplateRoseGold = <gregtech:gt.metaitem.01:17351>;
var GTplateBlackBronze = <gregtech:gt.metaitem.01:17352>;
var GTplateBismuthBronze = <gregtech:gt.metaitem.01:17353>;
var GTplateMagneticIron =  <gregtech:gt.metaitem.01:17354>;
var GTplateMagneticSteel = <gregtech:gt.metaitem.01:17355>;
var GTplateMagneticNeodymium = <gregtech:gt.metaitem.01:17067>;
var GTplateVanadiumGallium = <gregtech:gt.metaitem.01:17357>;
var GTplateYttriumBariumCuprate = <gregtech:gt.metaitem.01:17358>;
var GTplateNiobiumNitride = <gregtech:gt.metaitem.03:3359>;
var GTplateNiobiumTitanium = <gregtech:gt.metaitem.01:17360>;
var GTplateChromiumDioxide = <gregtech:gt.metaitem.03:3361>;
var GTplateForce = <gregtech:gt.metaitem.01:17521>;
var GTplateDeepIron = <gregtech:gt.metaitem.01:17829>;
var GTplateDesh = <gregtech:gt.metaitem.01:17884>;

#########################
#Shapeless Plate Recipes#
#########################
recipes.addShapeless(GTplateBeryllium, [ingotBeryllium, hammer]);
recipes.addShapeless(GTplateMagnesium, [ingotMagnesium, hammer]);
recipes.addShapeless(GTplateAluminium, [ingotAluminium, hammer]);
recipes.addShapeless(GTplateSilicon, [ingotSilicon, hammer]);
recipes.addShapeless(GTplateScandium, [ingotScandium, hammer]);
recipes.addShapeless(GTplateTitanium, [ingotTitanium, hammer]);
recipes.addShapeless(GTplateVanadium, [ingotVanadium, hammer]);
recipes.addShapeless(GTplateChrome, [ingotChrome, hammer]);
recipes.addShapeless(GTplateManganese, [ingotManganese, hammer]);
recipes.addShapeless(GTplateIron, [ingotIron, hammer]);
recipes.addShapeless(GTplateCobalt, [ingotCobalt, hammer]);
recipes.addShapeless(GTplateNickel, [ingotNickel, hammer]);
recipes.addShapeless(GTplateCopper, [ingotCopper, hammer]);
recipes.addShapeless(GTplateZinc, [ingotZinc, hammer]);
recipes.addShapeless(GTplateGallium, [ingotGallium, hammer]);
recipes.addShapeless(GTplateRubidium, [ingotRubidium, hammer]);
recipes.addShapeless(GTplateYttrium, [ingotYttrium, hammer]);
recipes.addShapeless(GTplateNiobium, [ingotNiobium, hammer]);
recipes.addShapeless(GTplateMolybdenum, [ingotMolybdenum, hammer]);
recipes.addShapeless(GTplateSilver, [ingotSilver, hammer]);
recipes.addShapeless(GTplateIndium, [ingotIndium, hammer]);
recipes.addShapeless(GTplateTin, [ingotTin, hammer]);
recipes.addShapeless(GTplateAntimony, [ingotAntimony, hammer]);
recipes.addShapeless(GTplateTellurium, [ingotTellurium, hammer]);
recipes.addShapeless(GTplateCaesium, [ingotCaesium, hammer]);
recipes.addShapeless(GTplateLanthanum, [ingotLanthanum, hammer]);
recipes.addShapeless(GTplateCerium, [ingotCerium, hammer]);
recipes.addShapeless(GTplatePraseodymium, [ingotPraseodymium, hammer]);
recipes.addShapeless(GTplateNeodymium, [ingotNeodymium, hammer]);
recipes.addShapeless(GTplatePromethium, [ingotPromethium, hammer]);
recipes.addShapeless(GTplateSamarium, [ingotSamarium, hammer]);
recipes.addShapeless(GTplateEuropium, [ingotEuropium, hammer]);
recipes.addShapeless(GTplateGadolinium, [ingotGadolinium, hammer]);
recipes.addShapeless(GTplateTerbium, [ingotTerbium, hammer]);
recipes.addShapeless(GTplateDysprosium, [ingotDysprosium, hammer]);
recipes.addShapeless(GTplateHolmium, [ingotHolmium, hammer]);
recipes.addShapeless(GTplateErbium, [ingotErbium, hammer]);
recipes.addShapeless(GTplateThulium, [ingotThulium, hammer]);
recipes.addShapeless(GTplateYtterbium, [ingotYtterbium, hammer]);
recipes.addShapeless(GTplateLuteium, [ingotLutetium, hammer]);
recipes.addShapeless(GTplateTantalum, [ingotTantalum, hammer]);
recipes.addShapeless(GTplateTungsten, [ingotTungsten, hammer]);
recipes.addShapeless(GTplateOsmium, [ingotOsmium, hammer]);
recipes.addShapeless(GTplateIridium, [ingotIridium, hammer]);
recipes.addShapeless(GTplatePlatinum, [ingotPlatinum, hammer]);
recipes.addShapeless(GTplateGold, [ingotGold, hammer]);
recipes.addShapeless(GTplateLead, [ingotLead, hammer]);
recipes.addShapeless(GTplateBismuth, [ingotBismuth, hammer]);
recipes.addShapeless(GTplateThorium, [ingotThorium, hammer]);
recipes.addShapeless(GTplateUranium235, [ingotUranium235, hammer]);
recipes.addShapeless(GTplateUranium238, [ingotUranium238, hammer]);
recipes.addShapeless(GTplatePlutonium244, [ingotPlutonium244, hammer]);
recipes.addShapeless(GTplatePlutonium241, [ingotPlutonium241, hammer]);
recipes.addShapeless(GTplateAmericium, [ingotAmericium, hammer]);
recipes.addShapeless(GTplateNeutronium, [ingotNeutronium, hammer]);
recipes.addShapeless(GTplateBronze, [ingotBronze, hammer]);
recipes.addShapeless(GTplateBrass, [ingotBrass, hammer]);
recipes.addShapeless(GTplateInvar, [ingotBrass, hammer]);
recipes.addShapeless(GTplateElectrium, [ingotElectrium, hammer]);
recipes.addShapeless(GTplateWroughtIron, [ingotWroughtIron, hammer]);
recipes.addShapeless(GTplateSteel, [ingotSteel, hammer]);
recipes.addShapeless(GTplateStainlessSteel, [ingotStainlessSteel, hammer]);
recipes.addShapeless(GTplatePigIron, [ingotPigIron, hammer]);
recipes.addShapeless(GTplateRedAlloy, [ingotRedAlloy, hammer]);
recipes.addShapeless(GTplateBlueAlloy, [ingotBlueAlloy, hammer]);
recipes.addShapeless(GTplateCupronickel, [ingotCupronickel, hammer]);
recipes.addShapeless(GTplateNichrome, [ingotNichrome, hammer]);
recipes.addShapeless(GTplateKanthal, [ingotKanthal, hammer]);
recipes.addShapeless(GTplateMagnalium, [ingotMagnalium, hammer]);
recipes.addShapeless(GTplateSolderingAlloy, [ingotSolderingAlloy, hammer]);
recipes.addShapeless(GTplateTungstenSteel, [ingotTungstenSteel, hammer]);
recipes.addShapeless(GTplateOsmiridium, [ingotOsmiridium, hammer]);
recipes.addShapeless(GTplateSunnarium, [ingotSunnarium, hammer]);
recipes.addShapeless(GTplateAdamantium, [ingotAdamantium, hammer]);
recipes.addShapeless(GTplateFluxedElectrum, [ingotFluxedElectrum, hammer]);
recipes.addShapeless(GTplateEnderium, [ingotEnderium, hammer]);
recipes.addShapeless(GTplateHSLASteel, [ingotHSLASteel, hammer]);
recipes.addShapeless(GTplateInfusedGold, [ingotInfusedGold, hammer]);
recipes.addShapeless(GTplateNaquadah, [ingotNaquadah, hammer]);
recipes.addShapeless(GTplateNaquadahAlloy, [ingotNaquadahAlloy, hammer]);
recipes.addShapeless(GTplateEnrichedNaquadah, [ingotEnrichedNaquadah, hammer]);
recipes.addShapeless(GTplateNaquadria, [ingotNaquadria, hammer]);
recipes.addShapeless(GTplateDuranium, [ingotDuranium, hammer]);
recipes.addShapeless(GTplateTritanium, [ingotTritanium, hammer]);
recipes.addShapeless(GTplateThaumium, [ingotThaumium, hammer]);
recipes.addShapeless(GTplateMithril, [ingotMithril, hammer]);
recipes.addShapeless(GTplateMidasium, [ingotMidasium, hammer]);
recipes.addShapeless(GTplateAstralSilver, [ingotAstralSilver, hammer]);
recipes.addShapeless(GTplateBlackSteel, [ingotBlackSteel, hammer]);
recipes.addShapeless(GTplateDamascusSteel, [ingotDamascusSteel, hammer]);
recipes.addShapeless(GTplateShadowIron, [ingotShadowIron, hammer]);
recipes.addShapeless(GTplateShadowSteel, [ingotShadowSteel, hammer]);
recipes.addShapeless(GTplateDarkIron, [ingotDarkIron, hammer]);
recipes.addShapeless(GTplateCobaltBrass, [ingotCobaltBrass, hammer]);
recipes.addShapeless(GTplateUltimet, [ingotUltimet, hammer]);
recipes.addShapeless(GTplateAnnealedCopper, [ingotAnnealedCopper, hammer]);
recipes.addShapeless(GTplateFieryBlood, [ingotFieryBlood, hammer]);
recipes.addShapeless(GTplateRedSteel, [ingotRedAlloy, hammer]);
recipes.addShapeless(GTplateBlueSteel, [ingotBlueSteel, hammer]);
recipes.addShapeless(GTplateSterlingSilver, [ingotSterlingSilver, hammer]);
recipes.addShapeless(GTplateRoseGold, [ingotRoseGold, hammer]);
recipes.addShapeless(GTplateBlackBronze, [ingotBlackBronze, hammer]);
recipes.addShapeless(GTplateBismuthBronze, [ingotBismuthBronze, hammer]);
recipes.addShapeless(GTplateMagneticIron, [ingotMagneticIron, hammer]);
recipes.addShapeless(GTplateMagneticSteel, [ingotMagneticSteel, hammer]);
recipes.addShapeless(GTplateMagneticNeodymium, [ingotMagneticNeodymium, hammer]);
recipes.addShapeless(GTplateVanadiumGallium, [ingotVanadiumGallium, hammer]);
recipes.addShapeless(GTplateYttriumBariumCuprate, [ingotYttriumBariumCuprate, hammer]);
recipes.addShapeless(GTplateNiobiumNitride, [ingotNiobiumNitride, hammer]);
recipes.addShapeless(GTplateNiobiumTitanium, [ingotNiobiumTitanium, hammer]);
recipes.addShapeless(GTplateChromiumDioxide, [ingotChromiumDioxide, hammer]);
recipes.addShapeless(GTplateForce, [ingotForce, hammer]);
recipes.addShapeless(GTplateDeepIron, [ingotDeepIron, hammer]);
recipes.addShapeless(GTplateDesh, [ingotDesh, hammer]);

######################
#Shaped Plate Removal#
######################
recipes.removeShaped(<ore:plateBeryllium>);
recipes.removeShaped(<ore:plateMagnesium>);
recipes.removeShaped(<ore:plateAluminium>);
recipes.removeShaped(<ore:plateSilicon>);
recipes.removeShaped(<ore:plateScandium>);
recipes.removeShaped(<ore:plateTitanium>);
recipes.removeShaped(<ore:plateVanadium>);
recipes.removeShaped(<ore:plateChrome>);
recipes.removeShaped(<ore:plateManganese>);
recipes.removeShaped(<ore:plateIron>);
recipes.removeShaped(<ore:plateCobalt>);
recipes.removeShaped(<ore:plateNickel>);
recipes.removeShaped(<ore:plateCopper>);
recipes.removeShaped(<ore:plateZinc>);
recipes.removeShaped(<ore:plateGallium>);
recipes.removeShaped(<ore:plateRubidium>);
recipes.removeShaped(<ore:plateYttrium>);
recipes.removeShaped(<ore:plateNiobium>);
recipes.removeShaped(<ore:plateMolybdenum>);
recipes.removeShaped(<ore:plateSilver>);
recipes.removeShaped(<ore:plateIndium>);
recipes.removeShaped(<ore:plateTin>);
recipes.removeShaped(<ore:plateAntimony>);
recipes.removeShaped(<ore:plateTellurium>);
recipes.removeShaped(<ore:plateCaesium>);
recipes.removeShaped(<ore:plateLanthanum>);
recipes.removeShaped(<ore:plateCerium>);
recipes.removeShaped(<ore:platePraseodymium>);
recipes.removeShaped(<ore:plateNeodymium>);
recipes.removeShaped(<ore:platePromethium>);
recipes.removeShaped(<ore:plateSamarium>);
recipes.removeShaped(<ore:plateEuropium>);
recipes.removeShaped(<ore:plateGadolinium>);
recipes.removeShaped(<ore:plateTerbium>);
recipes.removeShaped(<ore:plateDysprosium>);
recipes.removeShaped(<ore:plateHolmium>);
recipes.removeShaped(<ore:plateErbium>);
recipes.removeShaped(<ore:plateThulium>);
recipes.removeShaped(<ore:plateYttriumBariumCuprate>);
recipes.removeShaped(<ore:plateLuteium>);
recipes.removeShaped(<ore:plateTantalum>);
recipes.removeShaped(<ore:plateTungsten>);
recipes.removeShaped(<ore:plateOsmium>);
recipes.removeShaped(<ore:plateIridium>);
recipes.removeShaped(<ore:platePlatinum>);
recipes.removeShaped(<ore:plateGold>);
recipes.removeShaped(<ore:plateLead>);
recipes.removeShaped(<ore:plateBismuth>);
recipes.removeShaped(<ore:plateThorium>);
recipes.removeShaped(<ore:plateUranium235>);
recipes.removeShaped(<ore:plateUranium>);
recipes.removeShaped(<ore:platePlutonium>);
recipes.removeShaped(<ore:platePlutonium241>);
recipes.removeShaped(<ore:plateAmericium>);
recipes.removeShaped(<ore:plateNeutronium>);
recipes.removeShaped(<ore:plateBronze>);
recipes.removeShaped(<ore:plateBrass>);
recipes.removeShaped(<ore:plateInvar>);
recipes.removeShaped(<ore:plateElectrium>);
recipes.removeShaped(<ore:plateWroughtIron>);
recipes.removeShaped(<ore:plateSteel>);
recipes.removeShaped(<ore:plateStainlessSteel>);
recipes.removeShaped(<ore:platePigIron>);
recipes.removeShaped(<ore:plateRedAlloy>);
recipes.removeShaped(<ore:plateBlueAlloy>);
recipes.removeShaped(<ore:plateCupronickel>);
recipes.removeShaped(<ore:plateNichrome>);
recipes.removeShaped(<ore:plateKanthal>);
recipes.removeShaped(<ore:plateMagnalium>);
recipes.removeShaped(<ore:plateSolderingAlloy>);
recipes.removeShaped(<ore:plateTungstenSteel>);
recipes.removeShaped(<ore:plateOsmiridium>);
recipes.removeShaped(<ore:plateSunnarium>);
recipes.removeShaped(<ore:plateAdamantium>);
recipes.removeShaped(<ore:plateElectrumFlux>);
recipes.removeShaped(<ore:plateEnderium>);
recipes.removeShaped(<ore:plateHSLASteel>);
recipes.removeShaped(<ore:plateInfusedGold>);
recipes.removeShaped(<ore:plateNaquadah>);
recipes.removeShaped(<ore:plateNaquadahAlloy>);
recipes.removeShaped(<ore:plateNaquadahEnriched>);
recipes.removeShaped(<ore:plateNaquadria>);
recipes.removeShaped(<ore:plateDuranium>);
recipes.removeShaped(<ore:plateTritanium>);
recipes.removeShaped(<ore:plateThaumium>);
recipes.removeShaped(<ore:plateMithril>);
recipes.removeShaped(<ore:plateMidasium>);
recipes.removeShaped(<ore:plateAstralSilver>);
recipes.removeShaped(<ore:plateBlackSteel>);
recipes.removeShaped(<ore:plateDamascusSteel>);
recipes.removeShaped(<ore:plateShadowIron>);
recipes.removeShaped(<ore:plateShadowSteel>);
recipes.removeShaped(<ore:plateDarkIron>);
recipes.removeShaped(<ore:plateCobaltBrass>);
recipes.removeShaped(<ore:plateUltimet>);
recipes.removeShaped(<ore:plateAnnealedCopper>);
recipes.removeShaped(<ore:plateFieryBlood>);
recipes.removeShaped(<ore:plateRedSteel>);
recipes.removeShaped(<ore:plateBlueSteel>);
recipes.removeShaped(<ore:plateSterlingSilver>);
recipes.removeShaped(<ore:plateRoseGold>);
recipes.removeShaped(<ore:plateBlackBronze>);
recipes.removeShaped(<ore:plateBismuthBronze>);
recipes.removeShaped(<ore:plateIronMagnetic>);
recipes.removeShaped(<ore:plateSteelMagnetic>);
recipes.removeShaped(<ore:plateNeodymiumMagnetic>);
recipes.removeShaped(<ore:plateVanadiumGallium>);
recipes.removeShaped(<ore:plateNiobiumNitride>);
recipes.removeShaped(<ore:plateNiobiumTitanium>);
recipes.removeShaped(<ore:plateChromiumDioxide>);
recipes.removeShaped(<ore:plateForce>);
recipes.removeShaped(<ore:plateDeepIron>);
recipes.removeShaped(<ore:plateDesh>);

#############################
#Shaped Wire Cutting Removal#
#############################
recipes.removeShaped(wireCobalt);
recipes.removeShaped(wireLead);
recipes.removeShaped(wireTin);
recipes.removeShaped(wireZinc);
recipes.removeShaped(wireSolderingAlloy);
recipes.removeShaped(wireIron);
recipes.removeShaped(wireNickel);
recipes.removeShaped(wireCupronickel);
recipes.removeShaped(wireCopper);
recipes.removeShaped(wireAnnealedCopper);
recipes.removeShaped(wireKanthal);
recipes.removeShaped(wireGold);
recipes.removeShaped(wireElectrum);
recipes.removeShaped(wireSilver);
recipes.removeShaped(wireBlueAlloy);
recipes.removeShaped(wireNichrome);
recipes.removeShaped(wireSteel);
recipes.removeShaped(wireTungstenSteel);
recipes.removeShaped(wireTungsten);
recipes.removeShaped(wireAluminium);
recipes.removeShaped(wireOsmium);
recipes.removeShaped(wirePlatinum);
recipes.removeShaped(wireNaquadah);
recipes.removeShaped(wireNiobiumTitanium);
recipes.removeShaped(wireVanadiumGallium);
recipes.removeShaped(wireYttriumBariumCuprate);
recipes.removeShaped(wireRedAlloy);

########################
#Shapeless Wire Cutting#
########################
recipes.addShapeless(wireCobalt * 2, [GTplateCobalt, cutter]);
recipes.addShapeless(wireLead * 2, [GTplateLead, cutter]);
recipes.addShapeless(wireTin * 2, [GTplateTin, cutter]);
recipes.addShapeless(wireZinc * 2, [GTplateZinc, cutter]);
recipes.addShapeless(wireSolderingAlloy * 2, [GTplateSolderingAlloy, cutter]);
recipes.addShapeless(wireIron * 2, [GTplateIron, cutter]);
recipes.addShapeless(wireNickel * 2, [GTplateNickel, cutter]);
recipes.addShapeless(wireCupronickel * 2, [GTplateCupronickel, cutter]);
recipes.addShapeless(wireCopper * 2, [GTplateCopper, cutter]);
recipes.addShapeless(wireAnnealedCopper * 2, [GTplateAnnealedCopper, cutter]);
recipes.addShapeless(wireKanthal * 2, [GTplateKanthal, cutter]);
recipes.addShapeless(wireGold * 2, [GTplateGold, cutter]);
recipes.addShapeless(wireElectrum * 2, [GTplateElectrium, cutter]);
recipes.addShapeless(wireSilver * 2, [GTplateSilver, cutter]);
recipes.addShapeless(wireBlueAlloy * 2, [GTplateBlueAlloy, cutter]);
recipes.addShapeless(wireNichrome * 2, [GTplateNichrome, cutter]);
recipes.addShapeless(wireSteel * 2, [GTplateSteel, cutter]);
recipes.addShapeless(wireTungstenSteel * 2, [GTplateTungstenSteel, cutter]);
recipes.addShapeless(wireTungsten * 2, [GTplateTungsten, cutter]);
recipes.addShapeless(wireAluminium * 2, [GTplateAluminium, cutter]);
recipes.addShapeless(wireOsmium * 2, [GTplateOsmium, cutter]);
recipes.addShapeless(wirePlatinum * 2, [GTplatePlatinum, cutter]);
recipes.addShapeless(wireNaquadah * 2, [GTplateNaquadah, cutter]);
recipes.addShapeless(wireNiobiumTitanium * 2, [GTplateNiobiumTitanium, cutter]);
recipes.addShapeless(wireVanadiumGallium * 2, [GTplateVanadiumGallium, cutter]);
recipes.addShapeless(wireYttriumBariumCuprate * 2, [GTplateYttriumBariumCuprate, cutter]);
recipes.addShapeless(wireRedAlloy * 2, [GTplateRedAlloy, cutter]);

